### ISSUE TITLE
Column "GEOMETRY_TYPE" not found

### ISSUE THREAD

**Issue by nigelsim** [orbisgis/h2gis#1260]
I just upgraded to H2GIS 2.0.0 from 1.5.0, and I get the following error when initialising H2GIS as per the readme (and which previously worked).

```SQL
CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.factory.H2GISFunctions.load";
CALL H2GIS_SPATIAL();
```

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "GEOMETRY_TYPE" not found; SQL statement:
CREATE VIEW geometry_columns AS SELECT  TABLE_CATALOG f_table_catalog,  TABLE_SCHEMA f_table_schema,  TABLE_NAME f_table_name,  COLUMN_NAME f_geometry_column, 1 storage_type, CAST(FindGeometryMetadata(TABLE_CATALOG,TABLE_SCHEMA, TABLE_NAME,COLUMN_NAME, DATA_TYPE, GEOMETRY_TYPE,GEOMETRY_SRID)[1] AS INTEGER) as geometry_type, CAST(FindGeometryMetadata(TABLE_CATALOG,TABLE_SCHEMA, TABLE_NAME,COLUMN_NAME,DATA_TYPE, GEOMETRY_TYPE,GEOMETRY_SRID)[2] AS INTEGER) as coord_dimension, CAST(FindGeometryMetadata(TABLE_CATALOG,TABLE_SCHEMA, TABLE_NAME,COLUMN_NAME,DATA_TYPE, GEOMETRY_TYPE,GEOMETRY_SRID)[3] AS INTEGER) as srid, FindGeometryMetadata(TABLE_CATALOG,TABLE_SCHEMA, TABLE_NAME,COLUMN_NAME, DATA_TYPE, GEOMETRY_TYPE,GEOMETRY_SRID)[4] as type  FROM INFORMATION_SCHEMA.COLUMNS WHERE DATA_TYPE = 'GEOMETRY'; [42122-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:163)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:145)
	at org.h2.expression.function.JavaFunction.optimize(JavaFunction.java:64)
	at org.h2.expression.function.Function.optimize(Function.java:2594)
	at org.h2.expression.function.Function.optimize(Function.java:2594)
	at org.h2.expression.Alias.optimize(Alias.java:52)
	at org.h2.command.dml.Select.prepare(Select.java:1206)
	at org.h2.command.Parser.parseCreateView(Parser.java:6951)
	at org.h2.command.Parser.parseCreate(Parser.java:6223)
	at org.h2.command.Parser.parsePrepared(Parser.java:903)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2gis.functions.factory.H2GISFunctions.registerSpatialTables(H2GISFunctions.java:361)
	at org.h2gis.functions.factory.H2GISFunctions.load(H2GISFunctions.java:350)
	...
```

The dependency tree is as follows
```
+--- org.orbisgis:h2gis:2.0.0
|    +--- org.apache.commons:commons-compress:1.21
|    +--- org.orbisgis:cts:1.6.0
|    |    +--- org.slf4j:slf4j-api:1.7.32
|    |    \--- org.orbisgis:commons:1.2.0
|    |         +--- commons-io:commons-io:2.11.0
|    |         +--- org.apache.commons:commons-compress:1.21
|    |         \--- org.slf4j:slf4j-api:1.7.32
|    +--- com.h2database:h2:2.1.210
|    +--- com.fasterxml.jackson.core:jackson-core:2.13.0 -> 2.11.4
|    +--- org.locationtech.jts:jts-core:1.18.2
|    +--- org.orbisgis:poly2tri:0.4.0
|    |    \--- org.slf4j:slf4j-api:1.7.32
|    +--- org.orbisgis:h2gis-api:2.0.0
|    |    \--- com.h2database:h2:2.1.210
|    +--- org.orbisgis:h2gis-utilities:2.0.0
|    |    +--- org.locationtech.jts:jts-core:1.18.2
|    |    +--- com.h2database:h2:2.1.210
|    |    +--- org.orbisgis:h2gis-api:2.0.0 (*)
|    |    +--- org.slf4j:slf4j-api:1.7.32
|    |    +--- org.orbisgis:cts:1.6.0 (*)
|    |    +--- org.orbisgis:h2gis-test-utilities:2.0.0
|    |    |    +--- org.junit.jupiter:junit-jupiter-api:5.8.2 -> 5.4.2 (*)
|    |    |    +--- com.h2database:h2:2.1.210
|    |    |    \--- org.locationtech.jts:jts-core:1.18.2
|    |    \--- org.slf4j:slf4j-simple:1.7.32
|    |         \--- org.slf4j:slf4j-api:1.7.32
|    \--- org.slf4j:slf4j-simple:1.7.32 (*)
```

**Comment by ebocher** [comment]
Are you running H2GIS 2.0.0 on a fresh database or an old one ?

Are you using H2GIS deps from maven ?

What is your java version ? H2GIS needs at least JAVA 11.

**Comment by nigelsim** [comment]
It is on a fresh database, run as part of the test suite.

Java 11

Deps are from Gradle, but I guess you mean are they from the maven repo, in
which case yes.

I'll investigate further later tonight

**Comment by nigelsim** [comment]
Apologies. It appears that there was 2 H2 versions on the test classpath because I was pulling in the explicit H2GIS and H2 version using `testRuntime`. Switching to `runtime` seems to have fixed things.
