### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#547]
```
 5006788 [SwingWorker-pool-1-thread-6] INFO  g.c.o.s.a.ExecuteScriptProcess - Execute request 35/68: CREATE TABLE in_buffer(PK integer primary key, THE_GEOM geometry) AS SELECT ba.pk, ST_INTERSECTION(ST_BUFFER(ba.the_geom,2 * @EPSILON, 'join=mitre') ,ST_BUFFER(ST_SIDEBUFFER(CASEWHEN(mb.PK is null,ST_TOMULTISEGMENTS(ba.the_geom),ST_INTERSECTION(ST_BUFFER(ba.the_geom,10 * @EPSILON, 'join=mitre') ,ST_UNION(ST_TOMULTISEGMENTS(ST_HOLES(mb.the_geom)), ST_TOMULTISEGMENTS(ST_EXTERIORRING(mb.the_geom))))), -@BUFFER_IN),@EPSILON, 'join=mitre')) the_geom FROM BUILD_USR BA LEFT JOIN merged_buildings mb ON ba.PK = mb.PK
 5029731 [SwingWorker-pool-1-thread-6] ERROR g.c.o.s.a.ExecuteScriptProcess - Exception calling user-defined function: "singleSideBuffer(null, -6.005): null"; SQL statement:
CREATE TABLE in_buffer(PK integer primary key, THE_GEOM geometry) AS SELECT ba.pk, ST_INTERSECTION(ST_BUFFER(ba.the_geom,2 * @EPSILON, 'join=mitre') ,ST_BUFFER(ST_SIDEBUFFER(CASEWHEN(mb.PK is null,ST_TOMULTISEGMENTS(ba.the_geom),ST_INTERSECTION(ST_BUFFER(ba.the_geom,10 * @EPSILON, 'join=mitre') ,ST_UNION(ST_TOMULTISEGMENTS(ST_HOLES(mb.the_geom)), ST_TOMULTISEGMENTS(ST_EXTERIORRING(mb.the_geom))))), -@BUFFER_IN),@EPSILON, 'join=mitre')) the_geom FROM BUILD_USR BA LEFT JOIN merged_buildings mb ON ba.PK = mb.PK [90105-186]
 org.h2.jdbc.JdbcSQLException: Exception calling user-defined function: "singleSideBuffer(null, -6.005): null"; SQL statement:
CREATE TABLE in_buffer(PK integer primary key, THE_GEOM geometry) AS SELECT ba.pk, ST_INTERSECTION(ST_BUFFER(ba.the_geom,2 * @EPSILON, 'join=mitre') ,ST_BUFFER(ST_SIDEBUFFER(CASEWHEN(mb.PK is null,ST_TOMULTISEGMENTS(ba.the_geom),ST_INTERSECTION(ST_BUFFER(ba.the_geom,10 * @EPSILON, 'join=mitre') ,ST_UNION(ST_TOMULTISEGMENTS(ST_HOLES(mb.the_geom)), ST_TOMULTISEGMENTS(ST_EXTERIORRING(mb.the_geom))))), -@BUFFER_IN),@EPSILON, 'join=mitre')) the_geom FROM BUILD_USR BA LEFT JOIN merged_buildings mb ON ba.PK = mb.PK [90105-186]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convertInvocation(DbException.java:312)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:493)
	at org.h2.expression.JavaFunction.getValue(JavaFunction.java:38)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:426)
	at org.h2.expression.JavaFunction.getValue(JavaFunction.java:38)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:426)
	at org.h2.expression.JavaFunction.getValue(JavaFunction.java:38)
	at org.h2.expression.Alias.getValue(Alias.java:36)
	at org.h2.command.dml.Select.queryFlat(Select.java:581)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:686)
	at org.h2.command.dml.Query.query(Query.java:322)
	at org.h2.command.dml.Insert.insertRows(Insert.java:167)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:185)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2gis.utilities.wrapper.StatementWrapper.execute(StatementWrapper.java:115)
	at org.orbisgis.sqlconsole.actions.ExecuteScriptProcess.parseAndExecuteScript(ExecuteScriptProcess.java:124)
	at org.orbisgis.sqlconsole.actions.ExecuteScriptProcess.doInBackground(ExecuteScriptProcess.java:146)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at com.vividsolutions.jts.operation.buffer.BufferOp.computeGeometry(BufferOp.java:308)
	at com.vividsolutions.jts.operation.buffer.BufferOp.getResultGeometry(BufferOp.java:299)
	at com.vividsolutions.jts.operation.buffer.BufferOp.bufferOp(BufferOp.java:194)
	at org.h2gis.h2spatialext.function.spatial.processing.ST_SideBuffer.computeSingleSideBuffer(ST_SideBuffer.java:112)
	at org.h2gis.h2spatialext.function.spatial.processing.ST_SideBuffer.singleSideBuffer(ST_SideBuffer.java:61)
	at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:481)
	... 25 common frames omitted
```

**Comment by ebocher** [comment]
It seems you have a null input geometry on the sidebuffer function ?

**Comment by gpetit** [comment]
Yes. We are working on it. We have to take into account this unexpected case :-(

**Comment by ebocher** [comment]
There is a test on side buffer function no ?

**Comment by nicolas-f** [comment]
Yes there is a test. It seems that JTS raise a NPE. Maybe we have to check the type of geometry or catch NPE in H2GIS..

It should be interesting to be able to post a issue on jts with the corresponding geometry.

**Comment by ebocher** [comment]
Could you please post a test case ?

**Comment by ebocher** [comment]
Already valid ?

**Comment by ebocher** [comment]
Ping

**Comment by ebocher** [comment]
Ping
