### ISSUE TITLE
Invalid POM Error when Referencing H2GIS for an Embedded Database

### ISSUE THREAD

**Issue by michaeljmcd** [orbisgis/h2gis#608]
When I attempt to reference h2gis in my pom (for use with an embedded database), like so:

    <dependency>
      <groupId>org.orbisgis</groupId>
      <artifactId>h2spatial</artifactId>
      <version>1.2.3</version>
    </dependency>

I receive the following errors when I attempt to build my application:

     [WARNING] The POM for org.orbisgis:h2gis:jar:1.2.3 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.orbisgis:h2gis:1.2.3
     [FATAL] 'parent.artifactId' must be changed, the parent element cannot have the same  groupId:artifactId as the project. @ 

As indicated in the error, subdependencies (h2gis-ext, h2spatial, etc.) are not pulled in, which result in classpath errors when the geospatial extensions are enabled. It appears as though I can eliminate these errors on a temporary basis by adding dependencies to my pom for each of h2gis's dependencies, but this seems like a bit of a nasty workaround.

This is from running Maven 3.3.3 from the command line.

**Comment by nicolas-f** [comment]
Hi,

I'm sorry but I don't understand your error. We not have such issues with h2gis dependent projects. Please provide a sample project that raise this exception.

Thanks for report

Regards,

 Nicolas Fortin
 Lab-STICC – CNRS UMR 6285 et Ecole Centrale de Nantes
 GIS        http://orbisgis.org
 Spatial DB http://h2gis.org
 Noise      http://noisemap.orbisgis.org

**Comment by michaeljmcd** [comment]
I have an example, but github will not allow me to attach an archive or a text file directly to this message. 

So, here is what I did:

1. I generated a new application with the command `mvn archetype:generate -DgroupId=com.example -DartifactId=exampleApp -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`
2. I changed the `pom.xml` to look like http://pastebin.com/dQ6eKT1i
3. I changed the `App.java` to look like http://pastebin.com/2mzULXtC
4. I then ran `mvn clean install -X > build.log`
5. I then ran `java -jar target/exampleApp-1.0-SNAPSHOT-jar-with-dependencies.jar`, which produces this error message, confirming that classes are missing:

```
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Class "org.h2gis.h2spatialext.CreateSpatialExtension" not found; SQL statement:
CREATE ALIAS IF NOT EXISTS SPATIAL_INIT FOR "org.h2gis.h2spatialext.CreateSpatialExtension.initSpatialExtension" [90086-190]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:188)
        at org.h2.engine.FunctionAlias.loadClass(FunctionAlias.java:146)
        at org.h2.engine.FunctionAlias.load(FunctionAlias.java:122)
        at org.h2.engine.FunctionAlias.init(FunctionAlias.java:107)
        at org.h2.engine.FunctionAlias.newInstance(FunctionAlias.java:78)
        at org.h2.command.ddl.CreateFunctionAlias.update(CreateFunctionAlias.java:49)
        at org.h2.command.CommandContainer.update(CommandContainer.java:78)
        at org.h2.command.Command.executeUpdate(Command.java:253)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
        at com.example.App.main(App.java:22)
Caused by: java.lang.ClassNotFoundException: org.h2gis.h2spatialext.CreateSpatialExtension
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:181)
        ... 10 more
```

If you then find these entries in `build.log` as generated in step 4

```
[DEBUG] =======================================================================
[WARNING] The POM for org.orbisgis:h2spatial:jar:1.2.3 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.orbisgis:h2spatial:[unknown-version]
[FATAL] 'parent.artifactId' must be changed, the parent element cannot have the same groupId:artifactId as the project. @ org.orbisgis:h2gis:1.2.3
```

**Comment by nicolas-f** [comment]
This is because you require h2spatialext and link with only h2spatial.
If you want all features use this dependency:
```xml
    <dependency>
      <groupId>org.orbisgis</groupId>
      <artifactId>h2spatial-ext</artifactId>
      <version>1.2.3</version>
    </dependency>
```

**Comment by michaeljmcd** [comment]
Understood, but if you add a dependency so that the relevant section of the POM reads

```

    <dependency>
        <groupId>com.h2database</groupId>
        <artifactId>h2</artifactId>
        <version>1.4.190</version>
    </dependency>

    <!-- H2 Spatial Functions -->
    <dependency>
      <groupId>org.orbisgis</groupId>
      <artifactId>h2spatial</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
      <groupId>org.orbisgis</groupId>
      <artifactId>h2spatial-ext</artifactId>
      <version>1.2.3</version>
    </dependency>
```

You still receive warnings from Maven during build

```
[INFO] --- maven-assembly-plugin:2.4.1:single (make-assembly) @ exampleApp ---
[WARNING] Invalid POM for org.orbisgis:h2spatial:jar:1.2.3, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.orbisgis:h2spatial-ext:jar:1.2.3, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] Building jar: <PATHTO>\exampleApp\target\exampleApp-1.0-SNAPSHOT-jar-with-dependencies.jar
```

and a `ClassNotFoundException` at run time

```
$ java -jar target/exampleApp-1.0-SNAPSHOT-jar-with-dependencies.jar 
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Class "org.h2gis.h2spatialext.CreateSpatialExtension" not found; SQL statement:
CREATE ALIAS IF NOT EXISTS SPATIAL_INIT FOR "org.h2gis.h2spatialext.CreateSpatialExtension.initSpatialExtension" [90086-190]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:192)
        at org.h2.engine.FunctionAlias.loadClass(FunctionAlias.java:146)
        at org.h2.engine.FunctionAlias.load(FunctionAlias.java:122)
        at org.h2.engine.FunctionAlias.init(FunctionAlias.java:107)
        at org.h2.engine.FunctionAlias.newInstance(FunctionAlias.java:78)
        at org.h2.command.ddl.CreateFunctionAlias.update(CreateFunctionAlias.java:49)
        at org.h2.command.CommandContainer.update(CommandContainer.java:78)
        at org.h2.command.Command.executeUpdate(Command.java:253)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
        at com.example.App.main(App.java:22)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.h2gis.h2spatialext.CreateSpatialExtension.<clinit>(CreateSpatialExtension.java:87)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:181)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
```

The only way to make the application work as intended is to deeply add all inter-project dependencies by hand, as shown in my previous post.

**Comment by nicolas-f** [comment]
Hi,

I'm sorry but we are not able to have your error.

Try to build this project:
https://github.com/orbisgis/orbisgis-samples/tree/master/demoh2gis
```sh
mvn clean install
```

And execute with
```sh
mvn exec:exec
```

**Comment by michaeljmcd** [comment]
I get an identical error when I build the samples project after a fresh checkout (log below).

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building demoh2gis 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.orbisgis:h2spatial-ext:jar:1.2.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ demoh2gis ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ demoh2gis ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory <PATH TO>\orbisgis-samples\demoh2gis\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ demoh2gis ---
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to <PATH TO>\orbisgis-samples\demoh2gis\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ demoh2gis ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory <PATH TO>\orbisgis-samples\demoh2gis\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ demoh2gis ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ demoh2gis ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ demoh2gis ---
[INFO] Building jar: C:\Users\jisamm9\src\orbisgis-samples\demoh2gis\target\demoh2gis-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ demoh2gis ---
[INFO] Installing C:\Users\jisamm9\src\orbisgis-samples\demoh2gis\target\demoh2gis-1.0-SNAPSHOT.jar to C:\ProgramData\Eclipse\Projects_3.7.1\.m2\repository\org\orbisgis\demoh2gis\1.0-SNAPSHOT\demoh2gis-1.0-SNAPSHOT.jar
[INFO] Installing C:\Users\jisamm9\src\orbisgis-samples\demoh2gis\pom.xml to C:\ProgramData\Eclipse\Projects_3.7.1\.m2\repository\org\orbisgis\demoh2gis\1.0-SNAPSHOT\demoh2gis-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.444 s
[INFO] Finished at: 2015-11-30T14:18:52-06:00
[INFO] Final Memory: 11M/27M
[INFO] ------------------------------------------------------------------------
```

And the log from `exec:exec` is

```
[INFO] ------------------------------------------------------------------------
[INFO] Building demoh2gis 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.orbisgis:h2spatial-ext:jar:1.2.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ demoh2gis ---
java.lang.ClassNotFoundException: org.h2.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.orbisgis.demoh2gis.Main.main(Main.java:16)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.775 s
[INFO] Finished at: 2015-11-30T14:24:32-06:00
[INFO] Final Memory: 7M/17M
[INFO] ------------------------------------------------------------------------
```

Is it possible that the problem only exists with the version of the pom published to the Maven Central repository and not with the development version?

**Comment by nicolas-f** [comment]
Hi,

I even try under windows. There is no problem with demo project:

```
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. Tous droits réservés.

PS E:\github\orbisgis-samples\demoh2gis> mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building demoh2gis 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ demoh2gis ---
[INFO] Deleting E:\github\orbisgis-samples\demoh2gis\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ demoh2gis ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory E:\github\orbisgis-samples\demoh2gis\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ demoh2gis ---
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to E:\github\orbisgis-samples\demoh2gis\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ demoh2gis ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory E:\github\orbisgis-samples\demoh2gis\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ demoh2gis ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ demoh2gis ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ demoh2gis ---
[INFO] Building jar: E:\github\orbisgis-samples\demoh2gis\target\demoh2gis-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ demoh2gis ---
[INFO] Installing E:\github\orbisgis-samples\demoh2gis\target\demoh2gis-1.0-SNAPSHOT.jar to C:\Users\CUMU\.m2\repository
\org\orbisgis\demoh2gis\1.0-SNAPSHOT\demoh2gis-1.0-SNAPSHOT.jar
[INFO] Installing E:\github\orbisgis-samples\demoh2gis\pom.xml to C:\Users\CUMU\.m2\repository\org\orbisgis\demoh2gis\1.
0-SNAPSHOT\demoh2gis-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.224 s
[INFO] Finished at: 2015-12-02T10:40:59+01:00
[INFO] Final Memory: 13M/158M
[INFO] ------------------------------------------------------------------------
PS E:\github\orbisgis-samples\demoh2gis> mvn exec:exec
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building demoh2gis 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ demoh2gis ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Total length of roads: 29.253424165322986 m
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.342 s
[INFO] Finished at: 2015-12-02T10:41:13+01:00
[INFO] Final Memory: 6M/121M
[INFO] ------------------------------------------------------------------------
PS E:\github\orbisgis-samples\demoh2gis> mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: E:\Android\apache-maven-3.0.5-bin\apache-maven-3.0.5
Java version: 1.7.0_09, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_09\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
PS E:\github\orbisgis-samples\demoh2gis>
```
