### ISSUE TITLE
Cannot load GeoJSON

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/h2gis#675]
#This GeoJSON cannot be loaded into H2GIS:

```geojson
{
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 79.04200463708992,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655896568,
        "leq_id": 168,
        "marker-color": "#C5E805",
        "leq_100": 64.1989517211914,
        "leq_125": 71.39888000488281,
        "leq_160": 70.67826843261719,
        "leq_200": 72.09672546386719,
        "leq_250": 66.15381622314453,
        "leq_315": 65.47013092041016,
        "leq_400": 65.56007385253906,
        "leq_500": 63.37522506713867,
        "leq_630": 63.90888214111328,
        "leq_800": 62.77348327636719,
        "leq_1000": 61.991268157958984,
        "leq_1250": 62.70866394042969,
        "leq_1600": 63.18514633178711,
        "leq_2000": 64.54684448242188,
        "leq_2500": 64.50804901123047,
        "leq_3150": 64.38956451416016,
        "leq_4000": 59.998897552490234,
        "leq_5000": 60.81367874145508,
        "leq_6300": 62.20061492919922,
        "leq_8000": 54.597938537597656,
        "leq_10000": 13.839181900024414,
        "leq_12500": 13.261945724487305,
        "leq_16000": 13.135862350463867
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 85.1545979914708,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655897528,
        "leq_id": 169,
        "marker-color": "#EBD400",
        "leq_100": 73.575439453125,
        "leq_125": 78.34964752197266,
        "leq_160": 80.15424346923828,
        "leq_200": 78.0379409790039,
        "leq_250": 75.45632934570313,
        "leq_315": 72.87989044189453,
        "leq_400": 69.74015808105469,
        "leq_500": 64.67388153076172,
        "leq_630": 60.48469161987305,
        "leq_800": 56.084590911865234,
        "leq_1000": 53.43804931640625,
        "leq_1250": 51.55356216430664,
        "leq_1600": 50.98137283325195,
        "leq_2000": 50.06007766723633,
        "leq_2500": 49.00004196166992,
        "leq_3150": 47.05609893798828,
        "leq_4000": 45.81884002685547,
        "leq_5000": 45.1563835144043,
        "leq_6300": 45.118507385253906,
        "leq_8000": 40.76254653930664,
        "leq_10000": 35.66327667236328,
        "leq_12500": 35.15435028076172,
        "leq_16000": 34.897212982177734
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 88.5223139280462,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655898488,
        "leq_id": 170,
        "marker-color": "#EFAA00",
        "leq_100": 77.40330505371094,
        "leq_125": 81.32486724853516,
        "leq_160": 82.4485855102539,
        "leq_200": 81.77862548828125,
        "leq_250": 79.1686019897461,
        "leq_315": 77.79537963867188,
        "leq_400": 74.2901611328125,
        "leq_500": 72.08584594726563,
        "leq_630": 67.59555053710938,
        "leq_800": 62.21811294555664,
        "leq_1000": 56.40613555908203,
        "leq_1250": 53.52142333984375,
        "leq_1600": 55.52439498901367,
        "leq_2000": 50.04078674316406,
        "leq_2500": 49.958980560302734,
        "leq_3150": 47.58588409423828,
        "leq_4000": 45.43025588989258,
        "leq_5000": 44.31635284423828,
        "leq_6300": 43.7390251159668,
        "leq_8000": 39.101314544677734,
        "leq_10000": 31.321496963500977,
        "leq_12500": 30.7701473236084,
        "leq_16000": 30.505765914916992
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 88.21475681022179,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655899448,
        "leq_id": 171,
        "marker-color": "#EFAA00",
        "leq_100": 75.4771957397461,
        "leq_125": 81.7483901977539,
        "leq_160": 81.68172454833984,
        "leq_200": 82.05274200439453,
        "leq_250": 79.20404052734375,
        "leq_315": 76.38034057617188,
        "leq_400": 73.64982604980469,
        "leq_500": 71.20488739013672,
        "leq_630": 66.85353088378906,
        "leq_800": 60.400352478027344,
        "leq_1000": 57.09138107299805,
        "leq_1250": 54.073848724365234,
        "leq_1600": 49.758689880371094,
        "leq_2000": 48.15658187866211,
        "leq_2500": 49.26757049560547,
        "leq_3150": 50.548988342285156,
        "leq_4000": 48.841365814208984,
        "leq_5000": 50.372718811035156,
        "leq_6300": 43.34006118774414,
        "leq_8000": 38.80232238769531,
        "leq_10000": 29.00835609436035,
        "leq_12500": 28.478879928588867,
        "leq_16000": 28.2397518157959
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 85.50762999051389,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655900408,
        "leq_id": 172,
        "marker-color": "#EBD400",
        "leq_100": 74.88546752929688,
        "leq_125": 78.58580780029297,
        "leq_160": 79.05719757080078,
        "leq_200": 77.29692840576172,
        "leq_250": 77.07000732421875,
        "leq_315": 75.43588256835938,
        "leq_400": 71.775634765625,
        "leq_500": 69.26176452636719,
        "leq_630": 67.01737976074219,
        "leq_800": 61.410396575927734,
        "leq_1000": 58.129798889160156,
        "leq_1250": 54.2079963684082,
        "leq_1600": 54.77457046508789,
        "leq_2000": 54.8204231262207,
        "leq_2500": 54.45677947998047,
        "leq_3150": 54.40420150756836,
        "leq_4000": 52.78689956665039,
        "leq_5000": 51.20887756347656,
        "leq_6300": 48.529354095458984,
        "leq_8000": 41.858673095703125,
        "leq_10000": 23.838041305541992,
        "leq_12500": 23.239961624145508,
        "leq_16000": 22.934600830078125
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 81.68570797528183,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655901369,
        "leq_id": 173,
        "marker-color": "#E7FF00",
        "leq_100": 69.23311614990234,
        "leq_125": 76.71552276611328,
        "leq_160": 75.79912567138672,
        "leq_200": 74.40227508544922,
        "leq_250": 70.91729736328125,
        "leq_315": 68.11247253417969,
        "leq_400": 64.12867736816406,
        "leq_500": 61.06264114379883,
        "leq_630": 58.455345153808594,
        "leq_800": 55.965187072753906,
        "leq_1000": 56.76998519897461,
        "leq_1250": 53.885650634765625,
        "leq_1600": 57.85429000854492,
        "leq_2000": 56.81806182861328,
        "leq_2500": 55.759490966796875,
        "leq_3150": 53.346317291259766,
        "leq_4000": 51.814510345458984,
        "leq_5000": 50.04008865356445,
        "leq_6300": 48.5245361328125,
        "leq_8000": 42.47188949584961,
        "leq_10000": 29.18952178955078,
        "leq_12500": 28.650634765625,
        "leq_16000": 28.3793888092041
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 79.35133075924158,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655902329,
        "leq_id": 174,
        "marker-color": "#C5E805",
        "leq_100": 63.90614700317383,
        "leq_125": 69.687744140625,
        "leq_160": 74.68256378173828,
        "leq_200": 74.30673217773438,
        "leq_250": 70.85779571533203,
        "leq_315": 64.67572784423828,
        "leq_400": 61.74049377441406,
        "leq_500": 56.00607681274414,
        "leq_630": 53.51736068725586,
        "leq_800": 54.11384963989258,
        "leq_1000": 52.25947570800781,
        "leq_1250": 50.00495910644531,
        "leq_1600": 47.83668518066406,
        "leq_2000": 46.84468078613281,
        "leq_2500": 46.534141540527344,
        "leq_3150": 44.674285888671875,
        "leq_4000": 43.09204864501953,
        "leq_5000": 43.2689208984375,
        "leq_6300": 42.36881637573242,
        "leq_8000": 38.35343933105469,
        "leq_10000": 15.804949760437012,
        "leq_12500": 15.295221328735352,
        "leq_16000": 15.235172271728516
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 85.36481191655965,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655903289,
        "leq_id": 175,
        "marker-color": "#EBD400",
        "leq_100": 72.96358489990234,
        "leq_125": 78.4275131225586,
        "leq_160": 78.65509033203125,
        "leq_200": 78.35673522949219,
        "leq_250": 76.30127716064453,
        "leq_315": 74.197998046875,
        "leq_400": 73.4470443725586,
        "leq_500": 69.33229064941406,
        "leq_630": 63.74235916137695,
        "leq_800": 60.95743942260742,
        "leq_1000": 60.08573532104492,
        "leq_1250": 59.943294525146484,
        "leq_1600": 61.753963470458984,
        "leq_2000": 60.92157745361328,
        "leq_2500": 61.38080978393555,
        "leq_3150": 60.43061065673828,
        "leq_4000": 56.8224983215332,
        "leq_5000": 57.189781188964844,
        "leq_6300": 59.68102264404297,
        "leq_8000": 53.76148223876953,
        "leq_10000": 34.404109954833984,
        "leq_12500": 33.85392379760742,
        "leq_16000": 33.59896469116211
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 82.03794755152751,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655904249,
        "leq_id": 176,
        "marker-color": "#E7FF00",
        "leq_100": 69.50154876708984,
        "leq_125": 75.78950500488281,
        "leq_160": 74.6763916015625,
        "leq_200": 74.05156707763672,
        "leq_250": 74.79904174804688,
        "leq_315": 70.15087890625,
        "leq_400": 70.41846466064453,
        "leq_500": 63.1038932800293,
        "leq_630": 57.6888427734375,
        "leq_800": 56.70623779296875,
        "leq_1000": 57.696014404296875,
        "leq_1250": 59.34861755371094,
        "leq_1600": 57.425926208496094,
        "leq_2000": 56.30274200439453,
        "leq_2500": 56.50886917114258,
        "leq_3150": 53.86122512817383,
        "leq_4000": 51.97796630859375,
        "leq_5000": 50.418460845947266,
        "leq_6300": 52.36420822143555,
        "leq_8000": 46.90867233276367,
        "leq_10000": 21.13482666015625,
        "leq_12500": 20.812665939331055,
        "leq_16000": 20.6105899810791
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 85.73729758613521,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655905209,
        "leq_id": 177,
        "marker-color": "#EBD400",
        "leq_100": 74.6048583984375,
        "leq_125": 79.91511535644531,
        "leq_160": 79.94195556640625,
        "leq_200": 78.61101531982422,
        "leq_250": 76.26753997802734,
        "leq_315": 72.99662017822266,
        "leq_400": 69.31402587890625,
        "leq_500": 65.27412414550781,
        "leq_630": 59.38010025024414,
        "leq_800": 53.96453857421875,
        "leq_1000": 54.45947265625,
        "leq_1250": 53.8030891418457,
        "leq_1600": 50.73540496826172,
        "leq_2000": 51.895389556884766,
        "leq_2500": 52.320220947265625,
        "leq_3150": 49.277469635009766,
        "leq_4000": 47.697532653808594,
        "leq_5000": 45.35495376586914,
        "leq_6300": 45.99846649169922,
        "leq_8000": 42.93101501464844,
        "leq_10000": 27.933208465576172,
        "leq_12500": 27.35540199279785,
        "leq_16000": 27.07086944580078
      }
    },
    {
      "type": "Feature",
      "geometry": null,
      "properties": {
        "leq_mean": 89.03120327513898,
        "accuracy": 0,
        "location_utc": 0,
        "leq_utc": 1463655906170,
        "leq_id": 178,
        "marker-color": "#EFAA00",
        "leq_100": 76.4073715209961,
        "leq_125": 80.15514373779297,
        "leq_160": 83.86514282226563,
        "leq_200": 82.15755462646484,
        "leq_250": 79.98326873779297,
        "leq_315": 78.7275619506836,
        "leq_400": 74.85140228271484,
        "leq_500": 71.95274353027344,
        "leq_630": 66.98793029785156,
        "leq_800": 63.88633728027344,
        "leq_1000": 63.926483154296875,
        "leq_1250": 63.309295654296875,
        "leq_1600": 67.98342895507813,
        "leq_2000": 60.099178314208984,
        "leq_2500": 62.630882263183594,
        "leq_3150": 59.89934539794922,
        "leq_4000": 62.1864013671875,
        "leq_5000": 55.964271545410156,
        "leq_6300": 50.927650451660156,
        "leq_8000": 44.39337158203125,
        "leq_10000": 35.19732666015625,
        "leq_12500": 34.6005744934082,
        "leq_16000": 34.32241439819336
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -1.637021666666667,
          47.15928666666667,
          10.2
        ]
      },
      "properties": {
        "leq_mean": 90.40747637831151,
        "accuracy": 7.099999904632568,
        "location_utc": 1463655908000,
        "leq_utc": 1463655907130,
        "leq_id": 179,
        "marker-color": "#F37F00",
        "bearing": 0.87657195,
        "speed": 234.16,
        "leq_100": 76.83194732666016,
        "leq_125": 82.0689468383789,
        "leq_160": 82.47514343261719,
        "leq_200": 82.2070083618164,
        "leq_250": 78.7403335571289,
        "leq_315": 77.79939270019531,
        "leq_400": 75.52000427246094,
        "leq_500": 74.54205322265625,
        "leq_630": 71.80068969726563,
        "leq_800": 74.1656265258789,
        "leq_1000": 73.81553649902344,
        "leq_1250": 73.02767181396484,
        "leq_1600": 72.63093566894531,
        "leq_2000": 72.85362243652344,
        "leq_2500": 72.9808349609375,
        "leq_3150": 75.06314086914063,
        "leq_4000": 75.5537338256836,
        "leq_5000": 76.67915344238281,
        "leq_6300": 78.86624145507813,
        "leq_8000": 70.86571502685547,
        "leq_10000": 50.274410247802734,
        "leq_12500": 49.035884857177734,
        "leq_16000": 48.23350524902344
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -1.637021666666667,
          47.15928666666667,
          10.2
        ]
      },
      "properties": {
        "leq_mean": 97.41353643692344,
        "accuracy": 7.099999904632568,
        "location_utc": 1463655908000,
        "leq_utc": 1463655908090,
        "leq_id": 180,
        "marker-color": "#FB2A00",
        "bearing": 0.87657195,
        "speed": 234.16,
        "leq_100": 83.9887466430664,
        "leq_125": 92.81278991699219,
        "leq_160": 89.97296905517578,
        "leq_200": 85.88475036621094,
        "leq_250": 84.01581573486328,
        "leq_315": 81.59831237792969,
        "leq_400": 80.35589599609375,
        "leq_500": 79.99530029296875,
        "leq_630": 79.69717407226563,
        "leq_800": 78.66797637939453,
        "leq_1000": 79.50531005859375,
        "leq_1250": 79.12018585205078,
        "leq_1600": 78.79883575439453,
        "leq_2000": 80.8006362915039,
        "leq_2500": 80.15030670166016,
        "leq_3150": 80.91142272949219,
        "leq_4000": 80.4283447265625,
        "leq_5000": 81.92381286621094,
        "leq_6300": 84.47962188720703,
        "leq_8000": 77.55972290039063,
        "leq_10000": 46.3546257019043,
        "leq_12500": 45.52936553955078,
        "leq_16000": 45.17233657836914
      }
    }
  ]
}
```

**Comment by ebocher** [comment]
Is there an ouput error message ?

**Comment by nicolas-f** [comment]
Several issues

It expect order on json objects
```
 26514 [SwingWorker-pool-1-thread-3] ERROR o.orbisgis.dbjobs.jobs.ImportFiles - Cannot import the file
 java.sql.SQLException: Malformed GeoJSON file. Expected 'FeatureCollection', found '{'
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseMetadata(GeoJsonReaderDriver.java:214)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseGeoJson(GeoJsonReaderDriver.java:164)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.read(GeoJsonReaderDriver.java:132)
	at org.h2gis.drivers.geojson.GeoJsonDriverFunction.importFile(GeoJsonDriverFunction.java:82)
	at org.orbisgis.dbjobs.jobs.ImportFiles.doInBackground(ImportFiles.java:119)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

It does not handle null geometry

```
152018 [SwingWorker-pool-1-thread-5] ERROR o.orbisgis.dbjobs.jobs.ImportFiles - Cannot import the file
 java.sql.SQLException: Unsupported geometry : {
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseGeometryMetadata(GeoJsonReaderDriver.java:331)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.readFeatures(GeoJsonReaderDriver.java:266)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseMetadata(GeoJsonReaderDriver.java:209)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseGeoJson(GeoJsonReaderDriver.java:164)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.read(GeoJsonReaderDriver.java:132)
	at org.h2gis.drivers.geojson.GeoJsonDriverFunction.importFile(GeoJsonDriverFunction.java:82)
	at org.orbisgis.dbjobs.jobs.ImportFiles.doInBackground(ImportFiles.java:119)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
It does not quote field names
```
 211689 [SwingWorker-pool-1-thread-4] ERROR o.orbisgis.dbjobs.jobs.ImportFiles - Cannot import the file
 org.h2.jdbc.JdbcSQLException: Unknown data type: "-"; SQL statement:
CREATE TABLE "TRACK" (THE_GEOM GEOMETRY,LEQ_MEAN FLOAT8,ACCURACY FLOAT8,LOCATION_UTC INT,LEQ_UTC INT,LEQ_ID INT,MARKER-COLOR VARCHAR,BEARING FLOAT8,SPEED FLOAT8,LEQ_100 FLOAT8,LEQ_125 FLOAT8,LEQ_160 FLOAT8,LEQ_200 FLOAT8,LEQ_250 FLOAT8,LEQ_315 FLOAT8,LEQ_400 FLOAT8,LEQ_500 FLOAT8,LEQ_630 FLOAT8,LEQ_800 FLOAT8,LEQ_1000 FLOAT8,LEQ_1250 FLOAT8,LEQ_1600 FLOAT8,LEQ_2000 FLOAT8,LEQ_2500 FLOAT8,LEQ_3150 FLOAT8,LEQ_4000 FLOAT8,LEQ_5000 FLOAT8,LEQ_6300 FLOAT8,LEQ_8000 FLOAT8,LEQ_10000 FLOAT8,LEQ_12500 FLOAT8,LEQ_16000 FLOAT8) [50004-188]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4004)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3867)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5798)
	at org.h2.command.Parser.parseCreate(Parser.java:4162)
	at org.h2.command.Parser.parsePrepared(Parser.java:349)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.h2gis.utilities.wrapper.StatementWrapper.execute(StatementWrapper.java:115)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseMetadata(GeoJsonReaderDriver.java:233)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseGeoJson(GeoJsonReaderDriver.java:164)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.read(GeoJsonReaderDriver.java:132)
	at org.h2gis.drivers.geojson.GeoJsonDriverFunction.importFile(GeoJsonDriverFunction.java:82)
	at org.orbisgis.dbjobs.jobs.ImportFiles.doInBackground(ImportFiles.java:119)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

It does not support long type
```
 289011 [SwingWorker-pool-1-thread-6] ERROR o.orbisgis.dbjobs.jobs.ImportFiles - Cannot import the file
 com.fasterxml.jackson.core.JsonParseException: Numeric value (1463655908000) out of range of int
 at [Source: java.io.FileInputStream@6969bf2b; line: 18, column: 38]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:843)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:639)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.getValueAsInt(ParserMinimalBase.java:297)
	at com.fasterxml.jackson.core.JsonParser.getValueAsInt(JsonParser.java:1188)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseProperties(GeoJsonReaderDriver.java:532)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseFeature(GeoJsonReaderDriver.java:442)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseFeatures(GeoJsonReaderDriver.java:568)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseData(GeoJsonReaderDriver.java:896)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.parseGeoJson(GeoJsonReaderDriver.java:166)
	at org.h2gis.drivers.geojson.GeoJsonReaderDriver.read(GeoJsonReaderDriver.java:132)
	at org.h2gis.drivers.geojson.GeoJsonDriverFunction.importFile(GeoJsonDriverFunction.java:82)
	at org.orbisgis.dbjobs.jobs.ImportFiles.doInBackground(ImportFiles.java:119)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ebocher** [comment]
Fixed
