### ISSUE TITLE
Cannot convert to com.vividsolutions.jts.geom.Geometry

### ISSUE THREAD

**Issue by jbenoit2011** [orbisgis/h2gis#891]
Hello,

I'm posting here since I think it is more a bug than a mistake, but if I'm wrong tell me.

I am writing a test case which needs to test a class which runs this query:

```
           SELECT a.id, a.lvl
           FROM (
           SELECT am.admin_id
           FROM admin_mbr AS am
           WHERE ST_Contains(am.mbr,
          ST_GeomFromText('MULTIPOINT(48.861285633633926 2.3872681400191595, 48.8588575083531 2.3758241599809935)')
           ) = 1 ORDER BY ST_Area(am.mbr) LIMIT 1
           ) AS top_admin
           INNER JOIN admin_closure AS ac ON ac.descendant = top_admin.admin_id
           INNER JOIN admin AS a ON ac.ancestor = a.id
```
But the query parsing failed and throws this error:

```
   org.h2.jdbc.JdbcSQLException: Fonctionnalité non supportée: "converting to class com.vividsolutions.jts.geom.Geometry"
 Feature not supported: "converting to class com.vividsolutions.jts.geom.Geometry"; SQL statement:
 
           SELECT a.id, a.lvl
           FROM (
           SELECT am.admin_id
           FROM admin_mbr AS am
           WHERE ST_Contains(am.mbr,
           ST_GeomFromText('MULTIPOINT(48.861285633633926 2.3872681400191595, 48.8588575083531 2.3758241599809935)')
           ) = 1 ORDER BY ST_Area(am.mbr) LIMIT 1
           ) AS top_admin
           INNER JOIN admin_closure AS ac ON ac.descendant = top_admin.admin_id
           INNER JOIN admin AS a ON ac.ancestor = a.id
        [50100-197]
   at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
   at org.h2.message.DbException.get(DbException.java:179)
   at org.h2.message.DbException.get(DbException.java:155)
   at org.h2.message.DbException.getUnsupportedException(DbException.java:228)
   at org.h2.value.DataType.convertTo(DataType.java:1407)
   at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:435)
   at org.h2.expression.JavaFunction.getValue(JavaFunction.java:38)
   at org.h2.expression.Comparison.getValue(Comparison.java:239)
   at org.h2.expression.Expression.getBooleanValue(Expression.java:178)
   at org.h2.command.dml.Select.isConditionMet(Select.java:312)
```
It seems the `ST_GeomFromText` return type, which is `GEOMETRY`, cannot be converted correctly.
I did other tries with function returning another type than `GEOMETRY` and it did not failed on the parsing of this part, so I guess the `GEOMETRY` type is the problem.

But DDL queries, see below, which setup the tables works correctly.

Maybe because of the transition between com.vividsolutions.jts to org.locationtech.jts ?

If you want to reproduce the bug, here is the fixture DDL script I use:

```
    CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.factory.H2GISFunctions.load"
    CALL H2GIS_SPATIAL()

    DROP TABLE IF EXISTS admin
    CREATE TABLE admin (id int, lvl int)
    INSERT INTO admin VALUES (1, 1)
    INSERT INTO admin VALUES (4, 2)
    INSERT INTO admin VALUES (3, 3)
    INSERT INTO admin VALUES (2, 4)
    INSERT INTO admin VALUES (9, 5)

    DROP TABLE IF EXISTS admin_closure
    CREATE TABLE admin_closure (ancestor int, descendant int)
    INSERT INTO admin_closure VALUES (1, 4)
    INSERT INTO admin_closure VALUES (4, 3)
    INSERT INTO admin_closure VALUES (3, 2)
    INSERT INTO admin_closure VALUES (2, 9)

    DROP TABLE IF EXISTS admin_mbr
    CREATE TABLE admin_mbr (admin_id int, mbr polygon)
    INSERT INTO admin_mbr VALUES (1, 'POLYGON((41.371582 -5.142222,51.092804 -5.142222,51.092804 9.561556,41.371582 9.561556,41.371582 -5.142222))')
    INSERT INTO admin_mbr VALUES (4, 'POLYGON((48.120081 1.44617,49.241504 1.44617,49.241504 3.559007,48.120081 3.559007,48.120081 1.44617))')
    INSERT INTO admin_mbr VALUES (3, 'POLYGON((48.815573 2.224199,48.902145 2.224199,48.902145 2.469921,48.815573 2.469921,48.815573 2.224199))')
    INSERT INTO admin_mbr VALUES (2, 'POLYGON((48.815573 2.224199,48.902145 2.224199,48.902145 2.469921,48.815573 2.469921,48.815573 2.224199))')
    INSERT INTO admin_mbr VALUES (9, 'POLYGON((48.848092 2.363854,48.872046 2.363854,48.872046 2.399214,48.848092 2.399214,48.848092 2.363854))')
```

Thank you.

Julien.

**Comment by ebocher** [comment]
Tested with the current H2GIS version 1.4.0-SNAPSHOT and the query works.
Please set your H2GIS version
