### ISSUE TITLE
1.4.0 not in Maven central?

### ISSUE THREAD

**Issue by wimdeblauwe** [orbisgis/h2gis#902]
Hi,

I want to update my Spring Boot project to use Spring Boot 1.5.13 (currently using 1.5.10). After the upgrade, my unit tests fail with:

     Caused by: org.h2.jdbc.JdbcSQLException: Feature not supported: "converting to class com.vividsolutions.jts.geom.Geometry"; SQL statement:

I am currently using `org.orbisgis:h2gis-ext:1.3.2`. 

https://github.com/orbisgis/h2gis/issues/891 claims that 1.4.0 might fix this.

I see a `1.4.0` has been released, but it is not in Maven central. Could this be added?

**Comment by SPalominos** [comment]
Thank you for the issue!
The release on Maven Central has just been done, so it should be available very soon.

**Comment by wimdeblauwe** [comment]
Still not there I am afraid (https://mvnrepository.com/artifact/org.orbisgis/h2gis-ext)

**Comment by SPalominos** [comment]
h2gis-ext module doesn't exist anymore, is has been merge in h2gis which 1.4.0 release has arrived on maven central : https://mvnrepository.com/artifact/org.orbisgis/h2gis/1.4.0

**Comment by wimdeblauwe** [comment]
Ah, thx. Could have waited a long time in that case :-)

But I am still having this issue:

```
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.NoClassDefFoundError: org/locationtech/jts/io/ParseException"; SQL statement:
insert into observation (category, date_time, description, location, severity, bot_id, id) values (?, ?, ?, ?, ?, ?, ?) [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:303)
	at org.h2.command.Command.executeUpdate(Command.java:274)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	... 72 more
Caused by: java.lang.NoClassDefFoundError: org/locationtech/jts/io/ParseException
	at org.h2.value.Value.convertTo(Value.java:1021)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	... 75 more
Caused by: java.lang.ClassNotFoundException: org.locationtech.jts.io.ParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 81 more
```

Using these dependencies:

```
<dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.orbisgis</groupId>
            <artifactId>h2gis</artifactId>
            <version>${h2gis.version}</version>
        </dependency>
```

h2 is version `1.4.197` (Default of Spring Boot).

**Comment by wimdeblauwe** [comment]
Update: Downgrading h2 to `1.4.196` makes it work again.

**Comment by wimdeblauwe** [comment]
[Release notes of h2](http://www.h2database.com/html/changelog.html) 1.4.197 show:

> PR #897: Update JTS to version 1.15.0 from LocationTech

Might be the reason?

**Comment by SPalominos** [comment]
Yes! H2:1.4.197 uses the last release of JTS:1.15.0 but this version introduce test failure on H2GIS tests. We are working on this issue : orbisgis/h2gis#865

**Comment by wimdeblauwe** [comment]
Ok, thanks for the great work!
