### ISSUE TITLE
Exception at polygon insert

### ISSUE THREAD

**Issue by tolotos-rgu** [orbisgis/h2gis#967]
I'm using h2gis-ext 1.3.2 (latest found in maven)
While running 

```
String sql = "INSERT INTO " + TABLE_NAME + " VALUES (1, 'POLYGON ((11.9807354 51.4576828,11.9807363 51.4573915,11.9809485 51.4573918,11.9809476 51.457683,11.9807354 51.4576828))');";

connection.createStatement().execute(sql);
```

I get the following exception

```
General error: "java.lang.NoSuchMethodError: com.vividsolutions.jts.geom.Geometry.apply(Lcom/vividsolutions/jts/geom/CoordinateSequenceFilter;)V"; SQL statement:
INSERT INTO Areas_With_ID VALUES (1, 'POLYGON ((11.9807354 51.4576828,11.9807363 51.4573915,11.9809485 51.4573918,11.9809476 51.457683,11.9807354 51.4576828))'); [50000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:291)
	at org.h2.command.Command.executeUpdate(Command.java:268)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
	at com.initka.bprocess.streetdataengine.database.handler.AreasWithID.load(AreasWithID.java:45)
	at com.initka.bprocess.streetdataengine.database.impl.StreetDataEngineDatabaseImpl.load(StreetDataEngineDatabaseImpl.java:79)
	at com.initka.bprocess.streetdataengine.database.loader.CreateStreetDataEngineDatabase.load(CreateStreetDataEngineDatabase.java:26)
	at com.initka.bprocess.streetdataengine.database.loader.CreateStreetDataEngineDatabase.main(CreateStreetDataEngineDatabase.java:56)
Caused by: java.lang.NoSuchMethodError: com.vividsolutions.jts.geom.Geometry.apply(Lcom/vividsolutions/jts/geom/CoordinateSequenceFilter;)V
	at org.h2.value.ValueGeometry.getDimensionCount(ValueGeometry.java:90)
	at org.h2.value.ValueGeometry.convertToWKB(ValueGeometry.java:83)
	at org.h2.value.ValueGeometry.get(ValueGeometry.java:77)
	at org.h2.value.ValueGeometry.get(ValueGeometry.java:103)
	at org.h2.value.Value.convertTo(Value.java:988)
	at org.h2.table.Column.convert(Column.java:167)
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	... 6 more

```

Any ideas?

**Comment by tolotos-rgu** [comment]
I found the issue. A component used in the modules has its own JTS with a renamed jar. This JTS is really old but needed in this version by the component. I devide my module (servlet) to get an own classpath.
