### ISSUE TITLE
Running H2Gis in H2 cluster mode

### ISSUE THREAD

**Issue by jcfandino** [orbisgis/h2gis#978]
Hi,
  I'm interested in using h2gis combined with H2's clustering / high availability mode (http://www.h2database.com/html/advanced.html#clustering).
So far I was not able to make it work when enabling h2gis functions. When I create the cluster it seems the extension statements are run in the target instance and fail:

```
org.h2.jdbc.JdbcSQLException: Function "ST_GEOMETRYTYPECODE" not found; SQL statement:

CREATE DOMAIN POLYGON AS GEOMETRY(3) CHECK (PUBLIC.ST_GEOMETRYTYPECODE(VALUE) = 3) [90022-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readJavaFunction(Parser.java:2699)
       ...
	at org.h2.tools.RunScript.execute(RunScript.java:172)
	at org.h2.tools.CreateCluster.performTransfer(CreateCluster.java:136)
	at org.h2.tools.CreateCluster.process(CreateCluster.java:113)
	at org.h2.tools.CreateCluster.runTool(CreateCluster.java:84)
	at com.github.jcfandino.TestH2GisApplication.main(TestH2GisApplication.java:35)
```

I made a simple example to reproduce the issue:
https://gist.github.com/jcfandino/129cb43a084337db55d34f70e9b083b3

Notice that by removing the line `H2GISFunctions.load(...)` the example works without a problem (when only using H2 native types).

Is supporting this use case something unlikely to happen?

Thanks.
JC

**Comment by ebocher** [comment]
@nicolas-f  any idea ?

**Comment by nicolas-f** [comment]
The H2GIS library must be added in all instances of H2.

But H2GIS has never been tested with h2 cluster mode.

**Comment by ebocher** [comment]
No traffic so I close it
