### ISSUE TITLE
ST_TRANSFORM doesn't transform point from NAD27 / Louisiana South to WGS84

### ISSUE THREAD

**Issue by PanFish** [orbisgis/h2gis#980]
We have a source srid: **NAD27 / Louisiana South (26782)** and destination srid: **WGS84 (4326)**. 

If we run query "**select ST_TRANSFORM(ST_SetSRID(ST_Point(489581,-55232), 26782),4326)**" then db throws exception:
```
"Exception calling user-defined function: "ST_Transform(conn3: url=jdbc:default:connection user=SA, POINT (489581 -55232), 4326): No transformation found from epsg:26782 to epsg:4326"; SQL statement:
select ST_TRANSFORM(ST_SetSRID(ST_Point(489581,-55232), 26782),4326) [90105-197] 90105/90105"
```
Terminal output:
```
6906 [H2 Console thread] WARN org.cts.op.CoordinateOperationFactory - Cannot create a CoordinateOperation from :
[epsg:26782] EPSG:26782
to :
[epsg:4326] EPSG:4326
6906 [H2 Console thread] WARN org.cts.op.CoordinateOperationFactory - No transformation found from epsg:26782 to epsg:4326
```
But on site "https://epsg.io/26782" we may translate this point to WGS84.

Is it incorrect work of database?

Code:
```
@Test
    public void testSomeMethod() {
        try (Connection c = DriverManager.getConnection("<CONNECTION_STRING>", "USERNAME", "PASSWORD")) {
            ST_Transform.ST_Transform(
                    c, 
                    ST_SetSRID.setSRID(ST_MakePoint.createPoint(489581.0, -55232.0), 26782), 
                    4326);
        } catch (SQLException ex) {
            fail("Connection refused..." + ex.getMessage());
        } catch (CoordinateOperationException ex) {
            ex.printStackTrace();
            fail("COE..." + ex.getMessage());
        }
}
```

Used:
h2gis-dist-1.5.0.jar

**Comment by PanFish** [comment]
File "DATABASENAME.trace.db."
```
org.h2.jdbc.JdbcSQLException: Exception calling user-defined function: "ST_Transform(conn9: url=jdbc:default:connection user=SA, POINT (489581 -55232), 4326): No transformation found from epsg:26782 to epsg:4326"; SQL statement:
select ST_TRANSFORM( ST_SetSRID( ST_POINT(489581, -55232), 26782), 4326 ) [90105-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convertInvocation(DbException.java:324)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:468)
	at org.h2.expression.JavaFunction.getValue(JavaFunction.java:38)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1460)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:79)
	at org.h2.result.LazyResult.next(LazyResult.java:59)
	at org.h2.command.dml.Select.queryFlat(Select.java:527)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:633)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114)
	at org.h2.command.dml.Query.query(Query.java:371)
	at org.h2.command.dml.Query.query(Query.java:333)
	at org.h2.command.CommandContainer.query(CommandContainer.java:114)
	at org.h2.command.Command.executeQuery(Command.java:202)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:227)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No transformation found from epsg:26782 to epsg:4326
	at org.cts.op.CoordinateOperationFactory.createCoordinateOperations(CoordinateOperationFactory.java:96)
	at org.h2gis.functions.spatial.crs.ST_Transform.ST_Transform(ST_Transform.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:456)
	... 20 more
```

**Comment by ebocher** [comment]
Sorry but CTS doesn't support the  +units=us-ft +no_defs tag specified in the proj file for  https://epsg.io/26782
I will put an issue on the cts lib
