### ISSUE TITLE
Load Geojson H2GIS2.0

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/h2gis#985]
I have tried to load the attached file (with Geojson extension) in a H2GIS2.0 database and it fails in H2GIS2.0 whereas it works in OrbisGIS (using H2GIS 1.5).
The error message is the following:

> org.h2.jdbc.JdbcSQLDataException: Erreur lors de la conversion de données "POLYGON ((302209.4064592468 6726163.3186909575, 302181.15018460836 6726154.1754270345, 302147.72179885587 6726108.22947243, 302134.01647743426 6726048.879648991, 302086.4974649397 6726080.171038579, 302094.8357441396 6726168.005961145, 302056.5520390027 6726233.149474537, 302075.7956342455 6726272.286336695, 302146.7934365937 6726263.469174598, 302198.430762529 6726353.955013106, 302209.4064592468 6726353.146878232, 302209.4064592468 6726163.3186909575))"
Data conversion error converting "POLYGON ((302209.4064592468 6726163.3186909575, 302181.15018460836 6726154.1754270345, 302147.72179885587 6726108.22947243, 302134.01647743426 6726048.879648991, 302086.4974649397 6726080.171038579, 302094.8357441396 6726168.005961145, 302056.5520390027 6726233.149474537, 302075.7956342455 6726272.286336695, 302146.7934365937 6726263.469174598, 302198.430762529 6726353.955013106, 302209.4064592468 6726353.146878232, 302209.4064592468 6726163.3186909575))"; SQL statement:
DROP TABLE IF EXISTS VEGET; [22018-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:455)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.value.ValueGeometry.getFromGeometry(ValueGeometry.java:104)
	at org.h2.value.DataType.convertToValue1(DataType.java:1239)
	at org.h2.value.DataType.convertToValue(DataType.java:1133)
	at org.h2.jdbc.JdbcPreparedStatement.setObject(JdbcPreparedStatement.java:535)
	at org.h2gis.functions.io.geojson.GeoJsonReaderDriver.parseFeatures(GeoJsonReaderDriver.java:913)
	at org.h2gis.functions.io.geojson.GeoJsonReaderDriver.parseData(GeoJsonReaderDriver.java:1253)
	at org.h2gis.functions.io.geojson.GeoJsonReaderDriver.parseGeoJson(GeoJsonReaderDriver.java:156)
	at org.h2gis.functions.io.geojson.GeoJsonReaderDriver.read(GeoJsonReaderDriver.java:119)
	at org.h2gis.functions.io.geojson.GeoJsonDriverFunction.importFile(GeoJsonDriverFunction.java:98)
	at org.h2gis.functions.io.geojson.GeoJsonRead.readGeoJson(GeoJsonRead.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:460)
	at org.h2.expression.function.JavaFunction.getValue(JavaFunction.java:40)
	at org.h2.command.dml.Call.query(Call.java:64)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:44)
	at org.h2.command.CommandList.update(CommandList.java:63)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2gis.utilities.wrapper.StatementWrapper.execute(StatementWrapper.java:109)
	at groovy.sql.Sql.execute(Sql.java:2274)
	at groovy.sql.Sql$execute.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at tempo.run(tempo.groovy:15)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
	at groovy.lang.GroovyShell.run(GroovyShell.java:518)
	at groovy.lang.GroovyShell.run(GroovyShell.java:497)
	at groovy.lang.GroovyShell.run(GroovyShell.java:170)
	at groovy.lang.GroovyShell$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at groovy.ui.Console$_runScriptImpl_closure16.doCall(Console.groovy:1005)
	at groovy.ui.Console$_runScriptImpl_closure16.doCall(Console.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:99)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1028)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:408)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.lang.Thread.run(Thread.java:748)

[VEGET.txt](https://github.com/orbisgis/h2gis/files/3410076/VEGET.txt)

**Comment by ebocher** [comment]
Seems related to the dimension of the geometry. H2GIS 2.0 now doesn't support mixed geometry dimension or incorrect geometry schema as MULTIPOINT(0 0 12, 0 0 NaN). We will have to make a choice and fix the geojson driver for this type of pb.

**Comment by SPalominos** [comment]
That's right, in the sample file given, there are geometries with no Z values and other with Z values.
@j3r3m1 Did we fixed this issue when we met ?
