### ISSUE TITLE
java 11 issue

### ISSUE THREAD

**Issue by elisevincent** [orbisgis/h2gis#986]
When executing org.h2gis.functions.factory.H2GISFunctions.load(H2GISFunctions.java:353) in java 1.8, it works fine. When executing the same code in java 11, the following stack trace is thrown:

org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE DOMAIN IF NOT EXISTS POINT AS GEOMETRY(1[*]) CHECK (ST_GEOMETRYTYPECODE(VALUE) = 1); "; SQL statement:
CREATE DOMAIN IF NOT EXISTS POINT AS GEOMETRY(1) CHECK (ST_GeometryTypeCode(VALUE) = 1); [42000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.getSyntaxError(DbException.java:229)
	at org.h2.command.Parser.getSyntaxError(Parser.java:989)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:5649)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5254)
	at org.h2.command.Parser.parseCreateDomain(Parser.java:6142)
	at org.h2.command.Parser.parseCreate(Parser.java:5781)
	at org.h2.command.Parser.parsePrepared(Parser.java:846)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:764)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2gis.functions.factory.H2GISFunctions.registerGeometryType(H2GISFunctions.java:366)
	at org.h2gis.functions.factory.H2GISFunctions.load(H2GISFunctions.java:353)
	... 69 common frames omitted

Used versions: h2gis 1.5.0, h2gis-functions: 1.3.2, h2: 1.4.199

**Comment by katzyn** [comment]
h2gis 1.5.0 needs H2 1.4.197. It isn't compatible with H2 1.4.199.

**Comment by ebocher** [comment]
Sorry the team was on holidays.
Thanks a lot @katzyn
